CREATE TABLE EMP (
  EMPNO SERIAL PRIMARY KEY,
  ENAME VARCHAR(256),
  JOB VARCHAR(256),
  HIREDATE DATE,
  SAL INT)


CREATE TABLE EMP_ENCRYPTED (
  EMPNO INT PRIMARY KEY,
  ENAME VARCHAR(256),
  JOB VARCHAR(256),
  HIREDATE DATE,
  SAL_ENC BYTEA
);

CREATE TABLE EMP_PLAIN (
  EMPNO SERIAL PRIMARY KEY,
  ENAME VARCHAR(256),
  JOB VARCHAR(256),
  HIREDATE DATE,
  SAL INT)


CREATE TABLE SAL_ECB (
  ID SERIAL PRIMARY KEY,
  ENAME TEXT,
  SAL INT,
  SAL_ENC_ECB BYTEA
);
